"""

Revision ID: 02f62f67798a
Revises: 9abe67488899
Create Date: 2025-04-04 15:14:31.358790

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02f62f67798a'
down_revision = '9abe67488899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('login_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_img', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_balance'), 'user', ['balance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_balance'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###