"""

Revision ID: 9abe67488899
Revises: 
Create Date: 2025-04-01 11:33:08.268153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9abe67488899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalbalance',
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_globalbalance_balance'), 'globalbalance', ['balance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_globalbalance_balance'), table_name='globalbalance')
    op.drop_table('globalbalance')
    # ### end Alembic commands ###