"""

Revision ID: aa5583c8b004
Revises: e00554a33124
Create Date: 2025-04-13 23:25:34.790961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aa5583c8b004'
down_revision = 'e00554a33124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper',
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('open_access_pdf', sa.JSON(), nullable=True),
    sa.Column('fields_of_study', sa.JSON(), nullable=True),
    sa.Column('publication_types', sa.JSON(), nullable=True),
    sa.Column('publication_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_paper_id'), 'paper', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_title'), 'paper', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_title'), table_name='paper')
    op.drop_index(op.f('ix_paper_paper_id'), table_name='paper')
    op.drop_table('paper')
    op.drop_table('trial')
    # ### end Alembic commands ###