"""

Revision ID: cb57d6e83251
Revises: 88903503da95
Create Date: 2025-04-05 14:08:25.116910

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb57d6e83251'
down_revision = '88903503da95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'login_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'profile_img',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_user_balance', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_balance', 'user', ['balance'], unique=False)
    op.alter_column('user', 'profile_img',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'login_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###