"""

Revision ID: ebe15ed59aa5
Revises: aa5583c8b004
Create Date: 2025-04-13 23:28:32.354152

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ebe15ed59aa5'
down_revision = 'aa5583c8b004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper', 'paper_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('paper', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('paper', 'paper_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###